export const personajes = [
  {
    nombre: "Naruto Uzumaki",
    edad: 32,
    aldea: "Konoha",
    rango: "Séptimo Hokage",
    afiliacion: "Equipo 7",
    jutsu_destacado: "Rasengan",
    estado: "Vivo",
    imagen: "naruto.webp",
  },
  {
    nombre: "Sasuke Uchiha",
    edad: 32,
    aldea: "Konoha",
    rango: "Nómada",
    afiliacion: "Antigua Equipo 7, Taka",
    jutsu_destacado: "Chidori",
    estado: "Vivo",
    imagen: "sasuke.webp",
  },
  {
    nombre: "Sakura Haruno",
    edad: 32,
    aldea: "Konoha",
    rango: "Kunoichi Médico",
    afiliacion: "Equipo 7",
    jutsu_destacado: "Byakugou no Jutsu",
    estado: "Vivo",
    imagen: "sakura.webp",
  },
  {
    nombre: "Kakashi Hatake",
    edad: 54,
    aldea: "Konoha",
    rango: "Sexto Hokage (anterior)",
    afiliacion: "Equipo 7",
    jutsu_destacado: "Kamui",
    estado: "Vivo",
    imagen: "kakashi.webp",
  },
  {
    nombre: "Gaara",
    edad: 35,
    aldea: "Aldea de la Arena",
    rango: "Kazekage",
    afiliacion: "Aldea de la Arena",
    jutsu_destacado: "Sabaku Kyuu",
    estado: "Vivo",
    imagen: "gaara.webp",
  },
  {
    nombre: "Hinata Hyuga",
    edad: 32,
    aldea: "Konoha",
    rango: "Kunoichi",
    afiliacion: "Equipo 8",
    jutsu_destacado: "Gentle Fist",
    estado: "Vivo",
    imagen: "hinata.webp",
  },
  {
    nombre: "Shikamaru Nara",
    edad: 32,
    aldea: "Konoha",
    rango: "Jounin",
    afiliacion: "Equipo 10",
    jutsu_destacado: "Shadow Possession Jutsu",
    estado: "Vivo",
    imagen: "shikamaru.webp",
  },
  {
    nombre: "Tsunade Senju",
    edad: 75,
    aldea: "Konoha",
    rango: "Quinta Hokage (anterior)",
    afiliacion: "Equipo 7",
    jutsu_destacado: "Creation Rebirth",
    estado: "Vivo",
    imagen: "tsunade.webp",
  },
  {
    nombre: "Orochimaru",
    edad: 70,
    aldea: "Exiliado de Konoha",
    rango: "Sannin",
    afiliacion: "El Sonido, Otogakure",
    jutsu_destacado: "Edo Tensei",
    estado: "Vivo",
    imagen: "orochimaru.webp",
  },
  {
    nombre: "Jiraiya",
    edad: 54,
    aldea: "Konoha",
    rango: "Sannin",
    afiliacion: "Equipo 7",
    jutsu_destacado: "Rasengan",
    estado: "Fallecido",
    imagen: "jiraiya.webp",
  },
];
